version: '3'

vars:
  COMPOSE_FILE: deploy/docker-compose.yml

tasks:
  up:
    desc: "Поднять всю инфраструктуру и сервисы"
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} up -d --build

  down:
    desc: "Остановить и удалить все контейнеры"
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} down

  logs:
    desc: "Смотреть логи всех сервисов"
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} logs -f

  proto:go:
    desc: "Генерация gRPC-клиента на Go для service-account"
    cmds:
      - mkdir -p src/service-account/internal/infrastructure/grpc/pb
      - >
        protoc -I=proto 
        --go_out=src/service-account/internal/infrastructure/grpc/pb --go_opt=paths=source_relative 
        --go-grpc_out=src/service-account/internal/infrastructure/grpc/pb --go-grpc_opt=paths=source_relative 
        proto/card_vault/v1/card_vault.proto

  # --- Service Account ---
  run:account:
    desc: "Локальный запуск Service Account (без Docker)"
    dir: src/service-account
    cmds:
      - go run cmd/main.go

  up:account:
    desc: "Пересобрать и перезапустить Service Account"
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} up -d --build service-account

  sqlc:account:
    desc: "Генерация моделей БД через sqlc для Service Account"
    dir: src/service-account
    cmds:
      - sqlc generate

  logs:account:
    desc: "Логи Service Account"
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} logs -f service-account

  migrate-up:account:
    desc: "Накатить все миграции базы данных"
    cmds:
      - migrate -path src/service-account/migrations -database "postgresql://bank_admin:secretpassword@localhost:5499/accounts_db?sslmode=disable" up

  migrate-down:account:
    desc: "Откатить последнюю миграцию на 1 шаг"
    cmds:
      - migrate -path src/service-account/migrations -database "postgresql://bank_admin:secretpassword@localhost:5499/accounts_db?sslmode=disable" down 1

  swag:account:
    desc: "Сгенерировать документацию Swagger"
    dir: src/service-account
    cmds:
      - swag init -g cmd/service-account/main.go -o ./docs --parseDependency --parseInternal

  # ==========================================
  # Service Notification
  # ==========================================
  run:notification:
    desc: "Локальный запуск Service Notification (без Docker)"
    dir: src/service-notification
    cmds:
      - go run cmd/app/main.go

  logs:notification:
    desc: "Логи Service Notification"
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} logs -f service-notification

  up:notification:
    desc: "Пересобрать и перезапустить Service Notification"
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} up -d --build service-notification
# ==========================================
# Service Vault
# ==========================================

  logs:vault:
    desc: "Логи Service Vault"
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} logs -f service-card-secure

  up:vault:
    desc: "Пересобрать и перезапустить Service Vault"
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} up -d --build service-card-secure

  # ==========================================
  # Service Community
  # ==========================================

  run:community:
    desc: "Локальный запуск Service Community"
    dir: src/service-community
    cmds:
      - go run cmd/community/main.go

  up:community:
    desc: "Пересобрать Service Community"
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} up -d --build service-community

  logs:community:
    desc: "Логи Service Community"
    cmds:
      - docker-compose -f {{.COMPOSE_FILE}} logs -f service-community

  sqlc:community:
    desc: "Генерация через sqlc"
    dir: src/service-community
    cmds:
      - sqlc generate

  migrate-up:community:
    desc: "Накатить все миграции базы данных для Community"
    cmds:
      - migrate -path src/service-community/migrations -database "postgresql://bank_admin:secretpassword@localhost:5499/community_db?sslmode=disable" up

  migrate-down:community:
    desc: "Откатить последнюю миграцию для Community на 1 шаг"
    cmds:
      - migrate -path src/service-community/migrations -database "postgresql://bank_admin:secretpassword@localhost:5499/community_db?sslmode=disable" down 1

  swag:community:
    desc: "Сгенерировать документацию Swagger для Community"
    dir: src/service-community
    cmds:
      - swag init -g cmd/community/main.go -o ./docs --parseDependency --parseInternal