// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: card_vault/v1/card_vault.proto

package card_vault_pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentSystem string                 `protobuf:"bytes,1,opt,name=payment_system,json=paymentSystem,proto3" json:"payment_system,omitempty"`
	IsVirtual     bool                   `protobuf:"varint,2,opt,name=is_virtual,json=isVirtual,proto3" json:"is_virtual,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCardRequest) Reset() {
	*x = IssueCardRequest{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCardRequest) ProtoMessage() {}

func (x *IssueCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCardRequest.ProtoReflect.Descriptor instead.
func (*IssueCardRequest) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{0}
}

func (x *IssueCardRequest) GetPaymentSystem() string {
	if x != nil {
		return x.PaymentSystem
	}
	return ""
}

func (x *IssueCardRequest) GetIsVirtual() bool {
	if x != nil {
		return x.IsVirtual
	}
	return false
}

type IssueCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	PanMask       string                 `protobuf:"bytes,2,opt,name=pan_mask,json=panMask,proto3" json:"pan_mask,omitempty"`
	ExpiryMonth   int32                  `protobuf:"varint,3,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	ExpiryYear    int32                  `protobuf:"varint,4,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueCardResponse) Reset() {
	*x = IssueCardResponse{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueCardResponse) ProtoMessage() {}

func (x *IssueCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueCardResponse.ProtoReflect.Descriptor instead.
func (*IssueCardResponse) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{1}
}

func (x *IssueCardResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *IssueCardResponse) GetPanMask() string {
	if x != nil {
		return x.PanMask
	}
	return ""
}

func (x *IssueCardResponse) GetExpiryMonth() int32 {
	if x != nil {
		return x.ExpiryMonth
	}
	return 0
}

func (x *IssueCardResponse) GetExpiryYear() int32 {
	if x != nil {
		return x.ExpiryYear
	}
	return 0
}

type GetCardDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardDetailsRequest) Reset() {
	*x = GetCardDetailsRequest{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardDetailsRequest) ProtoMessage() {}

func (x *GetCardDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetCardDetailsRequest) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{2}
}

func (x *GetCardDetailsRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type GetCardDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pan           string                 `protobuf:"bytes,1,opt,name=pan,proto3" json:"pan,omitempty"`
	Cvv           string                 `protobuf:"bytes,2,opt,name=cvv,proto3" json:"cvv,omitempty"`
	ExpiryMonth   int32                  `protobuf:"varint,3,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	ExpiryYear    int32                  `protobuf:"varint,4,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCardDetailsResponse) Reset() {
	*x = GetCardDetailsResponse{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCardDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCardDetailsResponse) ProtoMessage() {}

func (x *GetCardDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCardDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetCardDetailsResponse) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{3}
}

func (x *GetCardDetailsResponse) GetPan() string {
	if x != nil {
		return x.Pan
	}
	return ""
}

func (x *GetCardDetailsResponse) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *GetCardDetailsResponse) GetExpiryMonth() int32 {
	if x != nil {
		return x.ExpiryMonth
	}
	return 0
}

func (x *GetCardDetailsResponse) GetExpiryYear() int32 {
	if x != nil {
		return x.ExpiryYear
	}
	return 0
}

type VerifyCardRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pan           string                 `protobuf:"bytes,1,opt,name=pan,proto3" json:"pan,omitempty"`
	Cvv           string                 `protobuf:"bytes,2,opt,name=cvv,proto3" json:"cvv,omitempty"`
	ExpiryMonth   int32                  `protobuf:"varint,3,opt,name=expiry_month,json=expiryMonth,proto3" json:"expiry_month,omitempty"`
	ExpiryYear    int32                  `protobuf:"varint,4,opt,name=expiry_year,json=expiryYear,proto3" json:"expiry_year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCardRequest) Reset() {
	*x = VerifyCardRequest{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCardRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCardRequest) ProtoMessage() {}

func (x *VerifyCardRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCardRequest.ProtoReflect.Descriptor instead.
func (*VerifyCardRequest) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyCardRequest) GetPan() string {
	if x != nil {
		return x.Pan
	}
	return ""
}

func (x *VerifyCardRequest) GetCvv() string {
	if x != nil {
		return x.Cvv
	}
	return ""
}

func (x *VerifyCardRequest) GetExpiryMonth() int32 {
	if x != nil {
		return x.ExpiryMonth
	}
	return 0
}

func (x *VerifyCardRequest) GetExpiryYear() int32 {
	if x != nil {
		return x.ExpiryYear
	}
	return 0
}

type VerifyCardResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	TokenId       string                 `protobuf:"bytes,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyCardResponse) Reset() {
	*x = VerifyCardResponse{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyCardResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyCardResponse) ProtoMessage() {}

func (x *VerifyCardResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyCardResponse.ProtoReflect.Descriptor instead.
func (*VerifyCardResponse) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{5}
}

func (x *VerifyCardResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

func (x *VerifyCardResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type UpdateCardStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardStatusRequest) Reset() {
	*x = UpdateCardStatusRequest{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardStatusRequest) ProtoMessage() {}

func (x *UpdateCardStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateCardStatusRequest) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCardStatusRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *UpdateCardStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateCardStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCardStatusResponse) Reset() {
	*x = UpdateCardStatusResponse{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCardStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCardStatusResponse) ProtoMessage() {}

func (x *UpdateCardStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCardStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateCardStatusResponse) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCardStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteCardDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardDataRequest) Reset() {
	*x = DeleteCardDataRequest{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardDataRequest) ProtoMessage() {}

func (x *DeleteCardDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardDataRequest.ProtoReflect.Descriptor instead.
func (*DeleteCardDataRequest) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteCardDataRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

type DeleteCardDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteCardDataResponse) Reset() {
	*x = DeleteCardDataResponse{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteCardDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteCardDataResponse) ProtoMessage() {}

func (x *DeleteCardDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteCardDataResponse.ProtoReflect.Descriptor instead.
func (*DeleteCardDataResponse) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteCardDataResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type SetPinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Pin           string                 `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPinRequest) Reset() {
	*x = SetPinRequest{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPinRequest) ProtoMessage() {}

func (x *SetPinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPinRequest.ProtoReflect.Descriptor instead.
func (*SetPinRequest) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{10}
}

func (x *SetPinRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *SetPinRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

type SetPinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetPinResponse) Reset() {
	*x = SetPinResponse{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetPinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetPinResponse) ProtoMessage() {}

func (x *SetPinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetPinResponse.ProtoReflect.Descriptor instead.
func (*SetPinResponse) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{11}
}

func (x *SetPinResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VerifyPinRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Pin           string                 `protobuf:"bytes,2,opt,name=pin,proto3" json:"pin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPinRequest) Reset() {
	*x = VerifyPinRequest{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPinRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPinRequest) ProtoMessage() {}

func (x *VerifyPinRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPinRequest.ProtoReflect.Descriptor instead.
func (*VerifyPinRequest) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyPinRequest) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

func (x *VerifyPinRequest) GetPin() string {
	if x != nil {
		return x.Pin
	}
	return ""
}

type VerifyPinResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsValid       bool                   `protobuf:"varint,1,opt,name=is_valid,json=isValid,proto3" json:"is_valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyPinResponse) Reset() {
	*x = VerifyPinResponse{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyPinResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyPinResponse) ProtoMessage() {}

func (x *VerifyPinResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyPinResponse.ProtoReflect.Descriptor instead.
func (*VerifyPinResponse) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyPinResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

type GetTokenByPanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pan           string                 `protobuf:"bytes,1,opt,name=pan,proto3" json:"pan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenByPanRequest) Reset() {
	*x = GetTokenByPanRequest{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenByPanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenByPanRequest) ProtoMessage() {}

func (x *GetTokenByPanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenByPanRequest.ProtoReflect.Descriptor instead.
func (*GetTokenByPanRequest) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{14}
}

func (x *GetTokenByPanRequest) GetPan() string {
	if x != nil {
		return x.Pan
	}
	return ""
}

type GetTokenByPanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TokenId       string                 `protobuf:"bytes,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTokenByPanResponse) Reset() {
	*x = GetTokenByPanResponse{}
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTokenByPanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTokenByPanResponse) ProtoMessage() {}

func (x *GetTokenByPanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_card_vault_v1_card_vault_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTokenByPanResponse.ProtoReflect.Descriptor instead.
func (*GetTokenByPanResponse) Descriptor() ([]byte, []int) {
	return file_card_vault_v1_card_vault_proto_rawDescGZIP(), []int{15}
}

func (x *GetTokenByPanResponse) GetTokenId() string {
	if x != nil {
		return x.TokenId
	}
	return ""
}

var File_card_vault_v1_card_vault_proto protoreflect.FileDescriptor

const file_card_vault_v1_card_vault_proto_rawDesc = "" +
	"\n" +
	"\x1ecard_vault/v1/card_vault.proto\x12\rcard_vault.v1\"X\n" +
	"\x10IssueCardRequest\x12%\n" +
	"\x0epayment_system\x18\x01 \x01(\tR\rpaymentSystem\x12\x1d\n" +
	"\n" +
	"is_virtual\x18\x02 \x01(\bR\tisVirtual\"\x8d\x01\n" +
	"\x11IssueCardResponse\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x19\n" +
	"\bpan_mask\x18\x02 \x01(\tR\apanMask\x12!\n" +
	"\fexpiry_month\x18\x03 \x01(\x05R\vexpiryMonth\x12\x1f\n" +
	"\vexpiry_year\x18\x04 \x01(\x05R\n" +
	"expiryYear\"2\n" +
	"\x15GetCardDetailsRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\"\x80\x01\n" +
	"\x16GetCardDetailsResponse\x12\x10\n" +
	"\x03pan\x18\x01 \x01(\tR\x03pan\x12\x10\n" +
	"\x03cvv\x18\x02 \x01(\tR\x03cvv\x12!\n" +
	"\fexpiry_month\x18\x03 \x01(\x05R\vexpiryMonth\x12\x1f\n" +
	"\vexpiry_year\x18\x04 \x01(\x05R\n" +
	"expiryYear\"{\n" +
	"\x11VerifyCardRequest\x12\x10\n" +
	"\x03pan\x18\x01 \x01(\tR\x03pan\x12\x10\n" +
	"\x03cvv\x18\x02 \x01(\tR\x03cvv\x12!\n" +
	"\fexpiry_month\x18\x03 \x01(\x05R\vexpiryMonth\x12\x1f\n" +
	"\vexpiry_year\x18\x04 \x01(\x05R\n" +
	"expiryYear\"J\n" +
	"\x12VerifyCardResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\x12\x19\n" +
	"\btoken_id\x18\x02 \x01(\tR\atokenId\"L\n" +
	"\x17UpdateCardStatusRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"4\n" +
	"\x18UpdateCardStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"2\n" +
	"\x15DeleteCardDataRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\"2\n" +
	"\x16DeleteCardDataResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"<\n" +
	"\rSetPinRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\"*\n" +
	"\x0eSetPinResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"?\n" +
	"\x10VerifyPinRequest\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId\x12\x10\n" +
	"\x03pin\x18\x02 \x01(\tR\x03pin\".\n" +
	"\x11VerifyPinResponse\x12\x19\n" +
	"\bis_valid\x18\x01 \x01(\bR\aisValid\"(\n" +
	"\x14GetTokenByPanRequest\x12\x10\n" +
	"\x03pan\x18\x01 \x01(\tR\x03pan\"2\n" +
	"\x15GetTokenByPanResponse\x12\x19\n" +
	"\btoken_id\x18\x01 \x01(\tR\atokenId2\xcb\x05\n" +
	"\x10CardVaultService\x12N\n" +
	"\tIssueCard\x12\x1f.card_vault.v1.IssueCardRequest\x1a .card_vault.v1.IssueCardResponse\x12]\n" +
	"\x0eGetCardDetails\x12$.card_vault.v1.GetCardDetailsRequest\x1a%.card_vault.v1.GetCardDetailsResponse\x12Q\n" +
	"\n" +
	"VerifyCard\x12 .card_vault.v1.VerifyCardRequest\x1a!.card_vault.v1.VerifyCardResponse\x12Z\n" +
	"\rGetTokenByPan\x12#.card_vault.v1.GetTokenByPanRequest\x1a$.card_vault.v1.GetTokenByPanResponse\x12c\n" +
	"\x10UpdateCardStatus\x12&.card_vault.v1.UpdateCardStatusRequest\x1a'.card_vault.v1.UpdateCardStatusResponse\x12]\n" +
	"\x0eDeleteCardData\x12$.card_vault.v1.DeleteCardDataRequest\x1a%.card_vault.v1.DeleteCardDataResponse\x12E\n" +
	"\x06SetPin\x12\x1c.card_vault.v1.SetPinRequest\x1a\x1d.card_vault.v1.SetPinResponse\x12N\n" +
	"\tVerifyPin\x12\x1f.card_vault.v1.VerifyPinRequest\x1a .card_vault.v1.VerifyPinResponseBdZbgithub.com/Adopten123/banking-system/service-account/internal/infrastructure/grpc/pb;card_vault_pbb\x06proto3"

var (
	file_card_vault_v1_card_vault_proto_rawDescOnce sync.Once
	file_card_vault_v1_card_vault_proto_rawDescData []byte
)

func file_card_vault_v1_card_vault_proto_rawDescGZIP() []byte {
	file_card_vault_v1_card_vault_proto_rawDescOnce.Do(func() {
		file_card_vault_v1_card_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_card_vault_v1_card_vault_proto_rawDesc), len(file_card_vault_v1_card_vault_proto_rawDesc)))
	})
	return file_card_vault_v1_card_vault_proto_rawDescData
}

var file_card_vault_v1_card_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_card_vault_v1_card_vault_proto_goTypes = []any{
	(*IssueCardRequest)(nil),         // 0: card_vault.v1.IssueCardRequest
	(*IssueCardResponse)(nil),        // 1: card_vault.v1.IssueCardResponse
	(*GetCardDetailsRequest)(nil),    // 2: card_vault.v1.GetCardDetailsRequest
	(*GetCardDetailsResponse)(nil),   // 3: card_vault.v1.GetCardDetailsResponse
	(*VerifyCardRequest)(nil),        // 4: card_vault.v1.VerifyCardRequest
	(*VerifyCardResponse)(nil),       // 5: card_vault.v1.VerifyCardResponse
	(*UpdateCardStatusRequest)(nil),  // 6: card_vault.v1.UpdateCardStatusRequest
	(*UpdateCardStatusResponse)(nil), // 7: card_vault.v1.UpdateCardStatusResponse
	(*DeleteCardDataRequest)(nil),    // 8: card_vault.v1.DeleteCardDataRequest
	(*DeleteCardDataResponse)(nil),   // 9: card_vault.v1.DeleteCardDataResponse
	(*SetPinRequest)(nil),            // 10: card_vault.v1.SetPinRequest
	(*SetPinResponse)(nil),           // 11: card_vault.v1.SetPinResponse
	(*VerifyPinRequest)(nil),         // 12: card_vault.v1.VerifyPinRequest
	(*VerifyPinResponse)(nil),        // 13: card_vault.v1.VerifyPinResponse
	(*GetTokenByPanRequest)(nil),     // 14: card_vault.v1.GetTokenByPanRequest
	(*GetTokenByPanResponse)(nil),    // 15: card_vault.v1.GetTokenByPanResponse
}
var file_card_vault_v1_card_vault_proto_depIdxs = []int32{
	0,  // 0: card_vault.v1.CardVaultService.IssueCard:input_type -> card_vault.v1.IssueCardRequest
	2,  // 1: card_vault.v1.CardVaultService.GetCardDetails:input_type -> card_vault.v1.GetCardDetailsRequest
	4,  // 2: card_vault.v1.CardVaultService.VerifyCard:input_type -> card_vault.v1.VerifyCardRequest
	14, // 3: card_vault.v1.CardVaultService.GetTokenByPan:input_type -> card_vault.v1.GetTokenByPanRequest
	6,  // 4: card_vault.v1.CardVaultService.UpdateCardStatus:input_type -> card_vault.v1.UpdateCardStatusRequest
	8,  // 5: card_vault.v1.CardVaultService.DeleteCardData:input_type -> card_vault.v1.DeleteCardDataRequest
	10, // 6: card_vault.v1.CardVaultService.SetPin:input_type -> card_vault.v1.SetPinRequest
	12, // 7: card_vault.v1.CardVaultService.VerifyPin:input_type -> card_vault.v1.VerifyPinRequest
	1,  // 8: card_vault.v1.CardVaultService.IssueCard:output_type -> card_vault.v1.IssueCardResponse
	3,  // 9: card_vault.v1.CardVaultService.GetCardDetails:output_type -> card_vault.v1.GetCardDetailsResponse
	5,  // 10: card_vault.v1.CardVaultService.VerifyCard:output_type -> card_vault.v1.VerifyCardResponse
	15, // 11: card_vault.v1.CardVaultService.GetTokenByPan:output_type -> card_vault.v1.GetTokenByPanResponse
	7,  // 12: card_vault.v1.CardVaultService.UpdateCardStatus:output_type -> card_vault.v1.UpdateCardStatusResponse
	9,  // 13: card_vault.v1.CardVaultService.DeleteCardData:output_type -> card_vault.v1.DeleteCardDataResponse
	11, // 14: card_vault.v1.CardVaultService.SetPin:output_type -> card_vault.v1.SetPinResponse
	13, // 15: card_vault.v1.CardVaultService.VerifyPin:output_type -> card_vault.v1.VerifyPinResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_card_vault_v1_card_vault_proto_init() }
func file_card_vault_v1_card_vault_proto_init() {
	if File_card_vault_v1_card_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_card_vault_v1_card_vault_proto_rawDesc), len(file_card_vault_v1_card_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_card_vault_v1_card_vault_proto_goTypes,
		DependencyIndexes: file_card_vault_v1_card_vault_proto_depIdxs,
		MessageInfos:      file_card_vault_v1_card_vault_proto_msgTypes,
	}.Build()
	File_card_vault_v1_card_vault_proto = out.File
	file_card_vault_v1_card_vault_proto_goTypes = nil
	file_card_vault_v1_card_vault_proto_depIdxs = nil
}
