// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: card_vault/v1/card_vault.proto

package card_vault_pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CardVaultService_IssueCard_FullMethodName        = "/card_vault.v1.CardVaultService/IssueCard"
	CardVaultService_GetCardDetails_FullMethodName   = "/card_vault.v1.CardVaultService/GetCardDetails"
	CardVaultService_VerifyCard_FullMethodName       = "/card_vault.v1.CardVaultService/VerifyCard"
	CardVaultService_UpdateCardStatus_FullMethodName = "/card_vault.v1.CardVaultService/UpdateCardStatus"
	CardVaultService_DeleteCardData_FullMethodName   = "/card_vault.v1.CardVaultService/DeleteCardData"
	CardVaultService_SetPin_FullMethodName           = "/card_vault.v1.CardVaultService/SetPin"
	CardVaultService_VerifyPin_FullMethodName        = "/card_vault.v1.CardVaultService/VerifyPin"
)

// CardVaultServiceClient is the client API for CardVaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CardVaultServiceClient interface {
	IssueCard(ctx context.Context, in *IssueCardRequest, opts ...grpc.CallOption) (*IssueCardResponse, error)
	GetCardDetails(ctx context.Context, in *GetCardDetailsRequest, opts ...grpc.CallOption) (*GetCardDetailsResponse, error)
	VerifyCard(ctx context.Context, in *VerifyCardRequest, opts ...grpc.CallOption) (*VerifyCardResponse, error)
	UpdateCardStatus(ctx context.Context, in *UpdateCardStatusRequest, opts ...grpc.CallOption) (*UpdateCardStatusResponse, error)
	DeleteCardData(ctx context.Context, in *DeleteCardDataRequest, opts ...grpc.CallOption) (*DeleteCardDataResponse, error)
	SetPin(ctx context.Context, in *SetPinRequest, opts ...grpc.CallOption) (*SetPinResponse, error)
	VerifyPin(ctx context.Context, in *VerifyPinRequest, opts ...grpc.CallOption) (*VerifyPinResponse, error)
}

type cardVaultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCardVaultServiceClient(cc grpc.ClientConnInterface) CardVaultServiceClient {
	return &cardVaultServiceClient{cc}
}

func (c *cardVaultServiceClient) IssueCard(ctx context.Context, in *IssueCardRequest, opts ...grpc.CallOption) (*IssueCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueCardResponse)
	err := c.cc.Invoke(ctx, CardVaultService_IssueCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardVaultServiceClient) GetCardDetails(ctx context.Context, in *GetCardDetailsRequest, opts ...grpc.CallOption) (*GetCardDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCardDetailsResponse)
	err := c.cc.Invoke(ctx, CardVaultService_GetCardDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardVaultServiceClient) VerifyCard(ctx context.Context, in *VerifyCardRequest, opts ...grpc.CallOption) (*VerifyCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyCardResponse)
	err := c.cc.Invoke(ctx, CardVaultService_VerifyCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardVaultServiceClient) UpdateCardStatus(ctx context.Context, in *UpdateCardStatusRequest, opts ...grpc.CallOption) (*UpdateCardStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCardStatusResponse)
	err := c.cc.Invoke(ctx, CardVaultService_UpdateCardStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardVaultServiceClient) DeleteCardData(ctx context.Context, in *DeleteCardDataRequest, opts ...grpc.CallOption) (*DeleteCardDataResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCardDataResponse)
	err := c.cc.Invoke(ctx, CardVaultService_DeleteCardData_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardVaultServiceClient) SetPin(ctx context.Context, in *SetPinRequest, opts ...grpc.CallOption) (*SetPinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetPinResponse)
	err := c.cc.Invoke(ctx, CardVaultService_SetPin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cardVaultServiceClient) VerifyPin(ctx context.Context, in *VerifyPinRequest, opts ...grpc.CallOption) (*VerifyPinResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyPinResponse)
	err := c.cc.Invoke(ctx, CardVaultService_VerifyPin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CardVaultServiceServer is the server API for CardVaultService service.
// All implementations must embed UnimplementedCardVaultServiceServer
// for forward compatibility.
type CardVaultServiceServer interface {
	IssueCard(context.Context, *IssueCardRequest) (*IssueCardResponse, error)
	GetCardDetails(context.Context, *GetCardDetailsRequest) (*GetCardDetailsResponse, error)
	VerifyCard(context.Context, *VerifyCardRequest) (*VerifyCardResponse, error)
	UpdateCardStatus(context.Context, *UpdateCardStatusRequest) (*UpdateCardStatusResponse, error)
	DeleteCardData(context.Context, *DeleteCardDataRequest) (*DeleteCardDataResponse, error)
	SetPin(context.Context, *SetPinRequest) (*SetPinResponse, error)
	VerifyPin(context.Context, *VerifyPinRequest) (*VerifyPinResponse, error)
	mustEmbedUnimplementedCardVaultServiceServer()
}

// UnimplementedCardVaultServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCardVaultServiceServer struct{}

func (UnimplementedCardVaultServiceServer) IssueCard(context.Context, *IssueCardRequest) (*IssueCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueCard not implemented")
}
func (UnimplementedCardVaultServiceServer) GetCardDetails(context.Context, *GetCardDetailsRequest) (*GetCardDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCardDetails not implemented")
}
func (UnimplementedCardVaultServiceServer) VerifyCard(context.Context, *VerifyCardRequest) (*VerifyCardResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyCard not implemented")
}
func (UnimplementedCardVaultServiceServer) UpdateCardStatus(context.Context, *UpdateCardStatusRequest) (*UpdateCardStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateCardStatus not implemented")
}
func (UnimplementedCardVaultServiceServer) DeleteCardData(context.Context, *DeleteCardDataRequest) (*DeleteCardDataResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteCardData not implemented")
}
func (UnimplementedCardVaultServiceServer) SetPin(context.Context, *SetPinRequest) (*SetPinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetPin not implemented")
}
func (UnimplementedCardVaultServiceServer) VerifyPin(context.Context, *VerifyPinRequest) (*VerifyPinResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method VerifyPin not implemented")
}
func (UnimplementedCardVaultServiceServer) mustEmbedUnimplementedCardVaultServiceServer() {}
func (UnimplementedCardVaultServiceServer) testEmbeddedByValue()                          {}

// UnsafeCardVaultServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CardVaultServiceServer will
// result in compilation errors.
type UnsafeCardVaultServiceServer interface {
	mustEmbedUnimplementedCardVaultServiceServer()
}

func RegisterCardVaultServiceServer(s grpc.ServiceRegistrar, srv CardVaultServiceServer) {
	// If the following call panics, it indicates UnimplementedCardVaultServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CardVaultService_ServiceDesc, srv)
}

func _CardVaultService_IssueCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardVaultServiceServer).IssueCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardVaultService_IssueCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardVaultServiceServer).IssueCard(ctx, req.(*IssueCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardVaultService_GetCardDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCardDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardVaultServiceServer).GetCardDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardVaultService_GetCardDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardVaultServiceServer).GetCardDetails(ctx, req.(*GetCardDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardVaultService_VerifyCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardVaultServiceServer).VerifyCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardVaultService_VerifyCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardVaultServiceServer).VerifyCard(ctx, req.(*VerifyCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardVaultService_UpdateCardStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCardStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardVaultServiceServer).UpdateCardStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardVaultService_UpdateCardStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardVaultServiceServer).UpdateCardStatus(ctx, req.(*UpdateCardStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardVaultService_DeleteCardData_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCardDataRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardVaultServiceServer).DeleteCardData(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardVaultService_DeleteCardData_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardVaultServiceServer).DeleteCardData(ctx, req.(*DeleteCardDataRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardVaultService_SetPin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetPinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardVaultServiceServer).SetPin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardVaultService_SetPin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardVaultServiceServer).SetPin(ctx, req.(*SetPinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CardVaultService_VerifyPin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyPinRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CardVaultServiceServer).VerifyPin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CardVaultService_VerifyPin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CardVaultServiceServer).VerifyPin(ctx, req.(*VerifyPinRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CardVaultService_ServiceDesc is the grpc.ServiceDesc for CardVaultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CardVaultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "card_vault.v1.CardVaultService",
	HandlerType: (*CardVaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "IssueCard",
			Handler:    _CardVaultService_IssueCard_Handler,
		},
		{
			MethodName: "GetCardDetails",
			Handler:    _CardVaultService_GetCardDetails_Handler,
		},
		{
			MethodName: "VerifyCard",
			Handler:    _CardVaultService_VerifyCard_Handler,
		},
		{
			MethodName: "UpdateCardStatus",
			Handler:    _CardVaultService_UpdateCardStatus_Handler,
		},
		{
			MethodName: "DeleteCardData",
			Handler:    _CardVaultService_DeleteCardData_Handler,
		},
		{
			MethodName: "SetPin",
			Handler:    _CardVaultService_SetPin_Handler,
		},
		{
			MethodName: "VerifyPin",
			Handler:    _CardVaultService_VerifyPin_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "card_vault/v1/card_vault.proto",
}
