// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: chats.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addChatMember = `-- name: AddChatMember :exec
INSERT INTO chat_members (chat_id, user_id, role)
VALUES ($1, $2, $3)
`

type AddChatMemberParams struct {
	ChatID pgtype.UUID `json:"chat_id"`
	UserID pgtype.UUID `json:"user_id"`
	Role   string      `json:"role"`
}

func (q *Queries) AddChatMember(ctx context.Context, arg AddChatMemberParams) error {
	_, err := q.db.Exec(ctx, addChatMember, arg.ChatID, arg.UserID, arg.Role)
	return err
}

const createChat = `-- name: CreateChat :one
INSERT INTO chats (type_id, title, avatar_url)
VALUES ($1, $2, $3)
    RETURNING id, type_id, title, avatar_url, last_message_at, created_at
`

type CreateChatParams struct {
	TypeID    int32       `json:"type_id"`
	Title     pgtype.Text `json:"title"`
	AvatarUrl pgtype.Text `json:"avatar_url"`
}

func (q *Queries) CreateChat(ctx context.Context, arg CreateChatParams) (Chat, error) {
	row := q.db.QueryRow(ctx, createChat, arg.TypeID, arg.Title, arg.AvatarUrl)
	var i Chat
	err := row.Scan(
		&i.ID,
		&i.TypeID,
		&i.Title,
		&i.AvatarUrl,
		&i.LastMessageAt,
		&i.CreatedAt,
	)
	return i, err
}

const createMessage = `-- name: CreateMessage :one
INSERT INTO messages (chat_id,
                      sender_id,
                      reply_to_message_id,
                      content,
                      media_attachments,
                      is_transfer,
                      transfer_amount,
                      transfer_currency,
                      idempotency_key,
                      transfer_transaction_id,
                      transfer_status)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11) RETURNING id, chat_id, sender_id, reply_to_message_id, content, media_attachments, is_transfer, transfer_amount, transfer_currency, idempotency_key, transfer_transaction_id, transfer_status, is_edited, created_at, deleted_at
`

type CreateMessageParams struct {
	ChatID                pgtype.UUID    `json:"chat_id"`
	SenderID              pgtype.UUID    `json:"sender_id"`
	ReplyToMessageID      pgtype.Int8    `json:"reply_to_message_id"`
	Content               pgtype.Text    `json:"content"`
	MediaAttachments      []byte         `json:"media_attachments"`
	IsTransfer            bool           `json:"is_transfer"`
	TransferAmount        pgtype.Numeric `json:"transfer_amount"`
	TransferCurrency      pgtype.Text    `json:"transfer_currency"`
	IdempotencyKey        pgtype.Text    `json:"idempotency_key"`
	TransferTransactionID pgtype.UUID    `json:"transfer_transaction_id"`
	TransferStatus        pgtype.Text    `json:"transfer_status"`
}

// Создает новое сообщение в чате (обычное или перевод)
func (q *Queries) CreateMessage(ctx context.Context, arg CreateMessageParams) (Message, error) {
	row := q.db.QueryRow(ctx, createMessage,
		arg.ChatID,
		arg.SenderID,
		arg.ReplyToMessageID,
		arg.Content,
		arg.MediaAttachments,
		arg.IsTransfer,
		arg.TransferAmount,
		arg.TransferCurrency,
		arg.IdempotencyKey,
		arg.TransferTransactionID,
		arg.TransferStatus,
	)
	var i Message
	err := row.Scan(
		&i.ID,
		&i.ChatID,
		&i.SenderID,
		&i.ReplyToMessageID,
		&i.Content,
		&i.MediaAttachments,
		&i.IsTransfer,
		&i.TransferAmount,
		&i.TransferCurrency,
		&i.IdempotencyKey,
		&i.TransferTransactionID,
		&i.TransferStatus,
		&i.IsEdited,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getChatMessages = `-- name: GetChatMessages :many
SELECT id,
       chat_id,
       sender_id,
       reply_to_message_id,
       content,
       media_attachments,
       is_transfer,
       transfer_amount,
       transfer_currency,
       idempotency_key,
       transfer_transaction_id,
       transfer_status,
       is_edited,
       created_at,
       deleted_at
FROM messages
WHERE chat_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC LIMIT $2
OFFSET $3
`

type GetChatMessagesParams struct {
	ChatID pgtype.UUID `json:"chat_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

// Получает историю сообщений конкретного чата с пагинацией (от новых к старым)
func (q *Queries) GetChatMessages(ctx context.Context, arg GetChatMessagesParams) ([]Message, error) {
	rows, err := q.db.Query(ctx, getChatMessages, arg.ChatID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Message
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ChatID,
			&i.SenderID,
			&i.ReplyToMessageID,
			&i.Content,
			&i.MediaAttachments,
			&i.IsTransfer,
			&i.TransferAmount,
			&i.TransferCurrency,
			&i.IdempotencyKey,
			&i.TransferTransactionID,
			&i.TransferStatus,
			&i.IsEdited,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
