// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Chat struct {
	ID            pgtype.UUID        `json:"id"`
	TypeID        int32              `json:"type_id"`
	Title         pgtype.Text        `json:"title"`
	AvatarUrl     pgtype.Text        `json:"avatar_url"`
	LastMessageAt pgtype.Timestamptz `json:"last_message_at"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ChatMember struct {
	ChatID            pgtype.UUID        `json:"chat_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	Role              string             `json:"role"`
	JoinedAt          pgtype.Timestamptz `json:"joined_at"`
	LastReadMessageID pgtype.Int8        `json:"last_read_message_id"`
}

type ChatType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Comment struct {
	ID              int64              `json:"id"`
	PostID          int64              `json:"post_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	ParentCommentID pgtype.Int8        `json:"parent_comment_id"`
	Content         string             `json:"content"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type Follow struct {
	FollowerID  pgtype.UUID        `json:"follower_id"`
	FollowingID pgtype.UUID        `json:"following_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type Message struct {
	ID                    int64              `json:"id"`
	ChatID                pgtype.UUID        `json:"chat_id"`
	SenderID              pgtype.UUID        `json:"sender_id"`
	ReplyToMessageID      pgtype.Int8        `json:"reply_to_message_id"`
	Content               pgtype.Text        `json:"content"`
	MediaAttachments      []byte             `json:"media_attachments"`
	IsTransfer            bool               `json:"is_transfer"`
	TransferAmount        pgtype.Numeric     `json:"transfer_amount"`
	TransferCurrency      pgtype.Text        `json:"transfer_currency"`
	IdempotencyKey        pgtype.Text        `json:"idempotency_key"`
	TransferTransactionID pgtype.UUID        `json:"transfer_transaction_id"`
	TransferStatus        pgtype.Text        `json:"transfer_status"`
	IsEdited              bool               `json:"is_edited"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
}

type Post struct {
	ID                 int64              `json:"id"`
	AuthorID           pgtype.UUID        `json:"author_id"`
	TypeID             int32              `json:"type_id"`
	Content            string             `json:"content"`
	MediaAttachments   []byte             `json:"media_attachments"`
	RelatedAssetTicker pgtype.Text        `json:"related_asset_ticker"`
	Status             string             `json:"status"`
	LikesCount         int32              `json:"likes_count"`
	CommentsCount      int32              `json:"comments_count"`
	IsPinned           bool               `json:"is_pinned"`
	IsEdited           bool               `json:"is_edited"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type PostLike struct {
	PostID    int64              `json:"post_id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type PostType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type Report struct {
	ID         int64              `json:"id"`
	ReporterID pgtype.UUID        `json:"reporter_id"`
	TargetType string             `json:"target_type"`
	TargetID   int64              `json:"target_id"`
	Reason     string             `json:"reason"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type UsersProfile struct {
	UserID      pgtype.UUID        `json:"user_id"`
	Username    string             `json:"username"`
	DisplayName pgtype.Text        `json:"display_name"`
	AvatarUrl   pgtype.Text        `json:"avatar_url"`
	Bio         pgtype.Text        `json:"bio"`
	IsVerified  bool               `json:"is_verified"`
	IsStaff     bool               `json:"is_staff"`
	IsPrivate   bool               `json:"is_private"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
