// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: posts.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPostLike = `-- name: AddPostLike :exec
INSERT INTO post_likes (post_id, user_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type AddPostLikeParams struct {
	PostID int64       `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) AddPostLike(ctx context.Context, arg AddPostLikeParams) error {
	_, err := q.db.Exec(ctx, addPostLike, arg.PostID, arg.UserID)
	return err
}

const createPost = `-- name: CreatePost :one
INSERT INTO posts (author_id, type_id, content, media_attachments, related_asset_ticker, status)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, author_id, type_id, content, media_attachments, related_asset_ticker, status, likes_count, comments_count, is_pinned, is_edited, created_at, updated_at, deleted_at
`

type CreatePostParams struct {
	AuthorID           pgtype.UUID `json:"author_id"`
	TypeID             int32       `json:"type_id"`
	Content            string      `json:"content"`
	MediaAttachments   []byte      `json:"media_attachments"`
	RelatedAssetTicker pgtype.Text `json:"related_asset_ticker"`
	Status             string      `json:"status"`
}

func (q *Queries) CreatePost(ctx context.Context, arg CreatePostParams) (Post, error) {
	row := q.db.QueryRow(ctx, createPost,
		arg.AuthorID,
		arg.TypeID,
		arg.Content,
		arg.MediaAttachments,
		arg.RelatedAssetTicker,
		arg.Status,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.TypeID,
		&i.Content,
		&i.MediaAttachments,
		&i.RelatedAssetTicker,
		&i.Status,
		&i.LikesCount,
		&i.CommentsCount,
		&i.IsPinned,
		&i.IsEdited,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const decrementPostLikes = `-- name: DecrementPostLikes :exec
UPDATE posts
SET likes_count = GREATEST(likes_count - 1, 0)
WHERE id = $1
`

func (q *Queries) DecrementPostLikes(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, decrementPostLikes, id)
	return err
}

const getPostByID = `-- name: GetPostByID :one
SELECT id, author_id, type_id, content, media_attachments, related_asset_ticker, status, likes_count, comments_count, is_pinned, is_edited, created_at, updated_at, deleted_at
FROM posts
WHERE id = $1
  AND deleted_at IS NULL LIMIT 1
`

func (q *Queries) GetPostByID(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRow(ctx, getPostByID, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.AuthorID,
		&i.TypeID,
		&i.Content,
		&i.MediaAttachments,
		&i.RelatedAssetTicker,
		&i.Status,
		&i.LikesCount,
		&i.CommentsCount,
		&i.IsPinned,
		&i.IsEdited,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const incrementPostLikes = `-- name: IncrementPostLikes :exec
UPDATE posts
SET likes_count = likes_count + 1
WHERE id = $1
`

func (q *Queries) IncrementPostLikes(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, incrementPostLikes, id)
	return err
}

const listFeedPosts = `-- name: ListFeedPosts :many
SELECT p.id,
       p.content,
       p.media_attachments,
       p.related_asset_ticker,
       p.status,
       p.likes_count,
       p.comments_count,
       p.is_pinned,
       p.created_at,
       u.user_id    AS author_id,
       u.username   AS author_username,
       u.avatar_url AS author_avatar
FROM posts p
         JOIN users_profile u ON p.author_id = u.user_id
WHERE p.deleted_at IS NULL
  AND p.status = 'published'
ORDER BY p.is_pinned DESC, p.created_at DESC LIMIT $1
OFFSET $2
`

type ListFeedPostsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListFeedPostsRow struct {
	ID                 int64              `json:"id"`
	Content            string             `json:"content"`
	MediaAttachments   []byte             `json:"media_attachments"`
	RelatedAssetTicker pgtype.Text        `json:"related_asset_ticker"`
	Status             string             `json:"status"`
	LikesCount         int32              `json:"likes_count"`
	CommentsCount      int32              `json:"comments_count"`
	IsPinned           bool               `json:"is_pinned"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	AuthorID           pgtype.UUID        `json:"author_id"`
	AuthorUsername     string             `json:"author_username"`
	AuthorAvatar       pgtype.Text        `json:"author_avatar"`
}

func (q *Queries) ListFeedPosts(ctx context.Context, arg ListFeedPostsParams) ([]ListFeedPostsRow, error) {
	rows, err := q.db.Query(ctx, listFeedPosts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFeedPostsRow
	for rows.Next() {
		var i ListFeedPostsRow
		if err := rows.Scan(
			&i.ID,
			&i.Content,
			&i.MediaAttachments,
			&i.RelatedAssetTicker,
			&i.Status,
			&i.LikesCount,
			&i.CommentsCount,
			&i.IsPinned,
			&i.CreatedAt,
			&i.AuthorID,
			&i.AuthorUsername,
			&i.AuthorAvatar,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removePostLike = `-- name: RemovePostLike :exec
DELETE
FROM post_likes
WHERE post_id = $1
  AND user_id = $2
`

type RemovePostLikeParams struct {
	PostID int64       `json:"post_id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) RemovePostLike(ctx context.Context, arg RemovePostLikeParams) error {
	_, err := q.db.Exec(ctx, removePostLike, arg.PostID, arg.UserID)
	return err
}
