// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: profiles.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUserProfile = `-- name: CreateUserProfile :one
INSERT INTO users_profile (user_id, username, display_name, avatar_url, bio, is_verified, is_staff, is_private)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING user_id, username, display_name, avatar_url, bio, is_verified, is_staff, is_private, created_at, updated_at
`

type CreateUserProfileParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Username    string      `json:"username"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Bio         pgtype.Text `json:"bio"`
	IsVerified  bool        `json:"is_verified"`
	IsStaff     bool        `json:"is_staff"`
	IsPrivate   bool        `json:"is_private"`
}

func (q *Queries) CreateUserProfile(ctx context.Context, arg CreateUserProfileParams) (UsersProfile, error) {
	row := q.db.QueryRow(ctx, createUserProfile,
		arg.UserID,
		arg.Username,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Bio,
		arg.IsVerified,
		arg.IsStaff,
		arg.IsPrivate,
	)
	var i UsersProfile
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsVerified,
		&i.IsStaff,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const followUser = `-- name: FollowUser :exec
INSERT INTO follows (follower_id, following_id)
VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type FollowUserParams struct {
	FollowerID  pgtype.UUID `json:"follower_id"`
	FollowingID pgtype.UUID `json:"following_id"`
}

func (q *Queries) FollowUser(ctx context.Context, arg FollowUserParams) error {
	_, err := q.db.Exec(ctx, followUser, arg.FollowerID, arg.FollowingID)
	return err
}

const getUserProfile = `-- name: GetUserProfile :one
SELECT user_id, username, display_name, avatar_url, bio, is_verified, is_staff, is_private, created_at, updated_at
FROM users_profile
WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserProfile(ctx context.Context, userID pgtype.UUID) (UsersProfile, error) {
	row := q.db.QueryRow(ctx, getUserProfile, userID)
	var i UsersProfile
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsVerified,
		&i.IsStaff,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const unfollowUser = `-- name: UnfollowUser :exec
DELETE
FROM follows
WHERE follower_id = $1
  AND following_id = $2
`

type UnfollowUserParams struct {
	FollowerID  pgtype.UUID `json:"follower_id"`
	FollowingID pgtype.UUID `json:"following_id"`
}

func (q *Queries) UnfollowUser(ctx context.Context, arg UnfollowUserParams) error {
	_, err := q.db.Exec(ctx, unfollowUser, arg.FollowerID, arg.FollowingID)
	return err
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users_profile
SET username     = COALESCE($2, username),
    display_name = COALESCE($3, display_name),
    avatar_url   = COALESCE($4, avatar_url),
    bio          = COALESCE($5, bio),
    is_private   = COALESCE($6, is_private),
    updated_at   = NOW()
WHERE user_id = $1 RETURNING user_id, username, display_name, avatar_url, bio, is_verified, is_staff, is_private, created_at, updated_at
`

type UpdateUserProfileParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	Username    pgtype.Text `json:"username"`
	DisplayName pgtype.Text `json:"display_name"`
	AvatarUrl   pgtype.Text `json:"avatar_url"`
	Bio         pgtype.Text `json:"bio"`
	IsPrivate   pgtype.Bool `json:"is_private"`
}

func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (UsersProfile, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.UserID,
		arg.Username,
		arg.DisplayName,
		arg.AvatarUrl,
		arg.Bio,
		arg.IsPrivate,
	)
	var i UsersProfile
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.DisplayName,
		&i.AvatarUrl,
		&i.Bio,
		&i.IsVerified,
		&i.IsStaff,
		&i.IsPrivate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
