// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: social.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReport = `-- name: CreateReport :one
INSERT INTO reports (reporter_id, target_type, target_id, reason)
VALUES ($1, $2, $3, $4) RETURNING id, reporter_id, target_type, target_id, reason, status, created_at
`

type CreateReportParams struct {
	ReporterID pgtype.UUID `json:"reporter_id"`
	TargetType string      `json:"target_type"`
	TargetID   int64       `json:"target_id"`
	Reason     string      `json:"reason"`
}

func (q *Queries) CreateReport(ctx context.Context, arg CreateReportParams) (Report, error) {
	row := q.db.QueryRow(ctx, createReport,
		arg.ReporterID,
		arg.TargetType,
		arg.TargetID,
		arg.Reason,
	)
	var i Report
	err := row.Scan(
		&i.ID,
		&i.ReporterID,
		&i.TargetType,
		&i.TargetID,
		&i.Reason,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}
