db:
  dsn: "postgresql://bank_admin:secretpassword@localhost:5499/accounts_db?sslmode=disable"
  max_conns: 20
  min_conns: 5
  max_conn_idle_time: 15m
  max_conn_lifetime: 1h

rabbitmq:
  url: "amqp://rmq_admin:secretpassword@rabbitmq:5672/"

exchanger:
  url: "http://exchanger:8085/api/v1/rates"
  timeout: 3s

