db:
  dsn: "postgresql://bank_admin:secretpassword@postgres:5432/accounts_db?sslmode=disable"
  max_conns: 20
  min_conns: 5
  max_conn_idle_time: 15m
  max_conn_lifetime: 1h

rabbitmq:
  url: "amqp://rmq_admin:secretpassword@rabbitmq:5672/"

exchanger:
  url: "http://service-exchanger:8085/api/v1/rates"
  timeout: 3s

vault:
  address: "service-card-secure:50051"
  timeout: 5s