// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO accounts (
    public_id, user_id, type_id, status_id, currency_code, name
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, public_id, user_id, type_id, status_id, currency_code, name, version, created_at, updated_at
`

type CreateAccountParams struct {
	PublicID     pgtype.UUID `json:"public_id"`
	UserID       pgtype.UUID `json:"user_id"`
	TypeID       pgtype.Int4 `json:"type_id"`
	StatusID     pgtype.Int4 `json:"status_id"`
	CurrencyCode pgtype.Text `json:"currency_code"`
	Name         pgtype.Text `json:"name"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (Account, error) {
	row := q.db.QueryRow(ctx, createAccount,
		arg.PublicID,
		arg.UserID,
		arg.TypeID,
		arg.StatusID,
		arg.CurrencyCode,
		arg.Name,
	)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.TypeID,
		&i.StatusID,
		&i.CurrencyCode,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one
SELECT id, public_id, user_id, type_id, status_id, currency_code, name, version, created_at, updated_at FROM accounts
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetAccountByID(ctx context.Context, id int64) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.TypeID,
		&i.StatusID,
		&i.CurrencyCode,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountByPublicID = `-- name: GetAccountByPublicID :one
SELECT id, public_id, user_id, type_id, status_id, currency_code, name, version, created_at, updated_at
FROM accounts
WHERE public_id = $1 LIMIT 1
`

func (q *Queries) GetAccountByPublicID(ctx context.Context, publicID pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByPublicID, publicID)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.PublicID,
		&i.UserID,
		&i.TypeID,
		&i.StatusID,
		&i.CurrencyCode,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
