// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_status.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBalanceForUpdate = `-- name: GetBalanceForUpdate :one
SELECT balance
FROM account_balances
WHERE account_id = $1 FOR UPDATE
`

func (q *Queries) GetBalanceForUpdate(ctx context.Context, accountID int64) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getBalanceForUpdate, accountID)
	var balance pgtype.Numeric
	err := row.Scan(&balance)
	return balance, err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
UPDATE accounts
SET status_id = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateAccountStatusParams struct {
	StatusID pgtype.Int4 `json:"status_id"`
	ID       int64       `json:"id"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error {
	_, err := q.db.Exec(ctx, updateAccountStatus, arg.StatusID, arg.ID)
	return err
}
