// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: account_status.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getBalanceForUpdate = `-- name: GetBalanceForUpdate :one
SELECT balance, credit_limit
FROM account_balances
WHERE account_id = $1 FOR UPDATE
`

type GetBalanceForUpdateRow struct {
	Balance     pgtype.Numeric `json:"balance"`
	CreditLimit pgtype.Numeric `json:"credit_limit"`
}

func (q *Queries) GetBalanceForUpdate(ctx context.Context, accountID int64) (GetBalanceForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getBalanceForUpdate, accountID)
	var i GetBalanceForUpdateRow
	err := row.Scan(&i.Balance, &i.CreditLimit)
	return i, err
}

const updateAccountStatus = `-- name: UpdateAccountStatus :exec
UPDATE accounts
SET status_id = $1,
    updated_at = now()
WHERE id = $2
`

type UpdateAccountStatusParams struct {
	StatusID pgtype.Int4 `json:"status_id"`
	ID       int64       `json:"id"`
}

func (q *Queries) UpdateAccountStatus(ctx context.Context, arg UpdateAccountStatusParams) error {
	_, err := q.db.Exec(ctx, updateAccountStatus, arg.StatusID, arg.ID)
	return err
}
