// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cards.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCard = `-- name: CreateCard :one
INSERT INTO cards (id,
                   account_id,
                   pan_mask,
                   expiry_date,
                   is_virtual,
                   status)
VALUES ($1, $2, $3, $4, $5, $6) RETURNING id, account_id, pan_mask, expiry_date, is_virtual, status, created_at
`

type CreateCardParams struct {
	ID         pgtype.UUID `json:"id"`
	AccountID  pgtype.Int8 `json:"account_id"`
	PanMask    pgtype.Text `json:"pan_mask"`
	ExpiryDate pgtype.Date `json:"expiry_date"`
	IsVirtual  pgtype.Bool `json:"is_virtual"`
	Status     pgtype.Text `json:"status"`
}

func (q *Queries) CreateCard(ctx context.Context, arg CreateCardParams) (Card, error) {
	row := q.db.QueryRow(ctx, createCard,
		arg.ID,
		arg.AccountID,
		arg.PanMask,
		arg.ExpiryDate,
		arg.IsVirtual,
		arg.Status,
	)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PanMask,
		&i.ExpiryDate,
		&i.IsVirtual,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getCardByID = `-- name: GetCardByID :one
SELECT
    id,
    account_id,
    pan_mask,
    expiry_date,
    is_virtual,
    status,
    created_at
FROM cards
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetCardByID(ctx context.Context, id pgtype.UUID) (Card, error) {
	row := q.db.QueryRow(ctx, getCardByID, id)
	var i Card
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PanMask,
		&i.ExpiryDate,
		&i.IsVirtual,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const updateCardStatus = `-- name: UpdateCardStatus :exec
UPDATE cards
SET status = $2
WHERE id = $1
`

type UpdateCardStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status pgtype.Text `json:"status"`
}

func (q *Queries) UpdateCardStatus(ctx context.Context, arg UpdateCardStatusParams) error {
	_, err := q.db.Exec(ctx, updateCardStatus, arg.ID, arg.Status)
	return err
}
