// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: credit_limit.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const updateCreditLimit = `-- name: UpdateCreditLimit :exec
UPDATE account_balances
SET credit_limit = $1,
    updated_at = now()
WHERE account_id = $2
`

type UpdateCreditLimitParams struct {
	CreditLimit pgtype.Numeric `json:"credit_limit"`
	AccountID   int64          `json:"account_id"`
}

func (q *Queries) UpdateCreditLimit(ctx context.Context, arg UpdateCreditLimitParams) error {
	_, err := q.db.Exec(ctx, updateCreditLimit, arg.CreditLimit, arg.AccountID)
	return err
}
