// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID int64 `json:"id"`
	// Для API
	PublicID     pgtype.UUID `json:"public_id"`
	UserID       pgtype.UUID `json:"user_id"`
	TypeID       pgtype.Int4 `json:"type_id"`
	StatusID     pgtype.Int4 `json:"status_id"`
	CurrencyCode pgtype.Text `json:"currency_code"`
	Name         pgtype.Text `json:"name"`
	// Optimistic Locking
	Version   pgtype.Int4        `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type AccountBalance struct {
	AccountID int64 `json:"account_id"`
	// Сумма всех postings. Кэш.
	Balance     pgtype.Numeric     `json:"balance"`
	CreditLimit pgtype.Numeric     `json:"credit_limit"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AccountStatus struct {
	ID int32 `json:"id"`
	// active, frozen, blocked, closed
	Name pgtype.Text `json:"name"`
}

type AccountType struct {
	ID int32 `json:"id"`
	// current, credit, savings
	Name pgtype.Text `json:"name"`
}

type Card struct {
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.Int8 `json:"account_id"`
	// 4276 **** **** 9999
	PanMask    pgtype.Text `json:"pan_mask"`
	ExpiryDate pgtype.Date `json:"expiry_date"`
	IsVirtual  pgtype.Bool `json:"is_virtual"`
	// active, blocked, expired
	Status    pgtype.Text        `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Currency struct {
	// ISO 4217: USD, RUB, JPY
	Code string      `json:"code"`
	Name pgtype.Text `json:"name"`
	// Количество копеек. 2 для USD/RUB, 0 для JPY
	Exponent pgtype.Int4 `json:"exponent"`
}

type Posting struct {
	ID            int64       `json:"id"`
	TransactionID pgtype.UUID `json:"transaction_id"`
	AccountID     pgtype.Int8 `json:"account_id"`
	// Отрицательное = списание, Положительное = зачисление
	Amount       pgtype.Numeric `json:"amount"`
	CurrencyCode pgtype.Text    `json:"currency_code"`
	// Курс к базовой валюте системы или кросс-курс
	ExchangeRate pgtype.Numeric `json:"exchange_rate"`
}

type RecurringPayment struct {
	ID                pgtype.UUID `json:"id"`
	SourceTypeID      int32       `json:"source_type_id"`
	SourceID          pgtype.UUID `json:"source_id"`
	DestinationTypeID pgtype.Int4 `json:"destination_type_id"`
	// Null если это вывод во вне
	DestinationID     pgtype.UUID        `json:"destination_id"`
	Amount            pgtype.Numeric     `json:"amount"`
	CurrencyCode      pgtype.Text        `json:"currency_code"`
	CategoryID        pgtype.Int4        `json:"category_id"`
	CronExpression    string             `json:"cron_expression"`
	NextExecutionTime pgtype.Timestamptz `json:"next_execution_time"`
	IsActive          pgtype.Bool        `json:"is_active"`
	Description       pgtype.Text        `json:"description"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type Transaction struct {
	ID                pgtype.UUID `json:"id"`
	SourceTypeID      pgtype.Int4 `json:"source_type_id"`
	SourceID          pgtype.UUID `json:"source_id"`
	DestinationTypeID pgtype.Int4 `json:"destination_type_id"`
	DestinationID     pgtype.UUID `json:"destination_id"`
	CategoryID        pgtype.Int4 `json:"category_id"`
	StatusID          pgtype.Int4 `json:"status_id"`
	Description       pgtype.Text `json:"description"`
	// Данные от провайдера, device_id и т.д.
	ExternalDetails []byte             `json:"external_details"`
	IdempotencyKey  pgtype.Text        `json:"idempotency_key"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type TransactionCategory struct {
	ID   int32       `json:"id"`
	Name pgtype.Text `json:"name"`
	// ISO 18245
	MccCode pgtype.Int4 `json:"mcc_code"`
}

type TransactionSourceType struct {
	ID   int32  `json:"id"`
	Name string `json:"name"`
}

type TransactionStatus struct {
	ID int32 `json:"id"`
	// pending, posted, failed, rolled_back
	Name pgtype.Text `json:"name"`
}

type User struct {
	// ID from SSO
	ID        pgtype.UUID        `json:"id"`
	Username  pgtype.Text        `json:"username"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
