// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: recurring_payments.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurringPayment = `-- name: CreateRecurringPayment :one
INSERT INTO recurring_payments (
    id,
    source_type_id,
    source_id,
    destination_type_id,
    destination_id,
    amount,
    currency_code,
    category_id,
    cron_expression,
    next_execution_time,
    description
) VALUES (
             $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
         ) RETURNING id, source_type_id, source_id, destination_type_id, destination_id, amount, currency_code, category_id, cron_expression, next_execution_time, is_active, description, created_at, updated_at
`

type CreateRecurringPaymentParams struct {
	ID                pgtype.UUID        `json:"id"`
	SourceTypeID      int32              `json:"source_type_id"`
	SourceID          pgtype.UUID        `json:"source_id"`
	DestinationTypeID pgtype.Int4        `json:"destination_type_id"`
	DestinationID     pgtype.UUID        `json:"destination_id"`
	Amount            pgtype.Numeric     `json:"amount"`
	CurrencyCode      pgtype.Text        `json:"currency_code"`
	CategoryID        pgtype.Int4        `json:"category_id"`
	CronExpression    string             `json:"cron_expression"`
	NextExecutionTime pgtype.Timestamptz `json:"next_execution_time"`
	Description       pgtype.Text        `json:"description"`
}

func (q *Queries) CreateRecurringPayment(ctx context.Context, arg CreateRecurringPaymentParams) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, createRecurringPayment,
		arg.ID,
		arg.SourceTypeID,
		arg.SourceID,
		arg.DestinationTypeID,
		arg.DestinationID,
		arg.Amount,
		arg.CurrencyCode,
		arg.CategoryID,
		arg.CronExpression,
		arg.NextExecutionTime,
		arg.Description,
	)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.SourceTypeID,
		&i.SourceID,
		&i.DestinationTypeID,
		&i.DestinationID,
		&i.Amount,
		&i.CurrencyCode,
		&i.CategoryID,
		&i.CronExpression,
		&i.NextExecutionTime,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDueRecurringPayments = `-- name: GetDueRecurringPayments :many
SELECT id, source_type_id, source_id, destination_type_id, destination_id, amount, currency_code, category_id, cron_expression, next_execution_time, is_active, description, created_at, updated_at
FROM recurring_payments
WHERE is_active = true
  AND next_execution_time <= NOW()
    FOR UPDATE SKIP LOCKED
LIMIT $1
`

func (q *Queries) GetDueRecurringPayments(ctx context.Context, limit int32) ([]RecurringPayment, error) {
	rows, err := q.db.Query(ctx, getDueRecurringPayments, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringPayment
	for rows.Next() {
		var i RecurringPayment
		if err := rows.Scan(
			&i.ID,
			&i.SourceTypeID,
			&i.SourceID,
			&i.DestinationTypeID,
			&i.DestinationID,
			&i.Amount,
			&i.CurrencyCode,
			&i.CategoryID,
			&i.CronExpression,
			&i.NextExecutionTime,
			&i.IsActive,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecurringPaymentByID = `-- name: GetRecurringPaymentByID :one
SELECT id, source_type_id, source_id, destination_type_id, destination_id, amount, currency_code, category_id, cron_expression, next_execution_time, is_active, description, created_at, updated_at
FROM recurring_payments
WHERE id = $1
`

func (q *Queries) GetRecurringPaymentByID(ctx context.Context, id pgtype.UUID) (RecurringPayment, error) {
	row := q.db.QueryRow(ctx, getRecurringPaymentByID, id)
	var i RecurringPayment
	err := row.Scan(
		&i.ID,
		&i.SourceTypeID,
		&i.SourceID,
		&i.DestinationTypeID,
		&i.DestinationID,
		&i.Amount,
		&i.CurrencyCode,
		&i.CategoryID,
		&i.CronExpression,
		&i.NextExecutionTime,
		&i.IsActive,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateRecurringPaymentNextRun = `-- name: UpdateRecurringPaymentNextRun :exec
UPDATE recurring_payments
SET next_execution_time = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateRecurringPaymentNextRunParams struct {
	ID                pgtype.UUID        `json:"id"`
	NextExecutionTime pgtype.Timestamptz `json:"next_execution_time"`
}

func (q *Queries) UpdateRecurringPaymentNextRun(ctx context.Context, arg UpdateRecurringPaymentNextRunParams) error {
	_, err := q.db.Exec(ctx, updateRecurringPaymentNextRun, arg.ID, arg.NextExecutionTime)
	return err
}

const updateRecurringPaymentStatus = `-- name: UpdateRecurringPaymentStatus :exec
UPDATE recurring_payments
SET is_active = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateRecurringPaymentStatusParams struct {
	ID       pgtype.UUID `json:"id"`
	IsActive pgtype.Bool `json:"is_active"`
}

func (q *Queries) UpdateRecurringPaymentStatus(ctx context.Context, arg UpdateRecurringPaymentStatusParams) error {
	_, err := q.db.Exec(ctx, updateRecurringPaymentStatus, arg.ID, arg.IsActive)
	return err
}
