// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transfers.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountForUpdate = `-- name: GetAccountForUpdate :one
SELECT a.id,
       a.status_id,
       a.currency_code,
       ab.balance,
       ab.credit_limit
FROM accounts a
JOIN account_balances ab ON a.id = ab.account_id
WHERE a.id = $1
FOR UPDATE
`

type GetAccountForUpdateRow struct {
	ID           int64          `json:"id"`
	StatusID     pgtype.Int4    `json:"status_id"`
	CurrencyCode pgtype.Text    `json:"currency_code"`
	Balance      pgtype.Numeric `json:"balance"`
	CreditLimit  pgtype.Numeric `json:"credit_limit"`
}

func (q *Queries) GetAccountForUpdate(ctx context.Context, id int64) (GetAccountForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAccountForUpdate, id)
	var i GetAccountForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.StatusID,
		&i.CurrencyCode,
		&i.Balance,
		&i.CreditLimit,
	)
	return i, err
}
