// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transactions.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addAccountBalance = `-- name: AddAccountBalance :one
UPDATE account_balances
SET balance    = balance + $1,
    updated_at = now()
WHERE account_id = $2 RETURNING account_id, balance, credit_limit, updated_at
`

type AddAccountBalanceParams struct {
	Balance   pgtype.Numeric `json:"balance"`
	AccountID int64          `json:"account_id"`
}

func (q *Queries) AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (AccountBalance, error) {
	row := q.db.QueryRow(ctx, addAccountBalance, arg.Balance, arg.AccountID)
	var i AccountBalance
	err := row.Scan(
		&i.AccountID,
		&i.Balance,
		&i.CreditLimit,
		&i.UpdatedAt,
	)
	return i, err
}

const createPosting = `-- name: CreatePosting :one
INSERT INTO postings (transaction_id, account_id, amount, currency_code, exchange_rate)
VALUES ($1, $2, $3, $4, $5) RETURNING id, transaction_id, account_id, amount, currency_code, exchange_rate
`

type CreatePostingParams struct {
	TransactionID pgtype.UUID    `json:"transaction_id"`
	AccountID     pgtype.Int8    `json:"account_id"`
	Amount        pgtype.Numeric `json:"amount"`
	CurrencyCode  pgtype.Text    `json:"currency_code"`
	ExchangeRate  pgtype.Numeric `json:"exchange_rate"`
}

func (q *Queries) CreatePosting(ctx context.Context, arg CreatePostingParams) (Posting, error) {
	row := q.db.QueryRow(ctx, createPosting,
		arg.TransactionID,
		arg.AccountID,
		arg.Amount,
		arg.CurrencyCode,
		arg.ExchangeRate,
	)
	var i Posting
	err := row.Scan(
		&i.ID,
		&i.TransactionID,
		&i.AccountID,
		&i.Amount,
		&i.CurrencyCode,
		&i.ExchangeRate,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (id, category_id, status_id, description, external_details, idempotency_key)
VALUES ($1, $2, $3, $4, $5,
        $6) RETURNING id, category_id, status_id, description, external_details, idempotency_key, created_at, updated_at
`

type CreateTransactionParams struct {
	ID              pgtype.UUID `json:"id"`
	CategoryID      pgtype.Int4 `json:"category_id"`
	StatusID        pgtype.Int4 `json:"status_id"`
	Description     pgtype.Text `json:"description"`
	ExternalDetails []byte      `json:"external_details"`
	IdempotencyKey  pgtype.Text `json:"idempotency_key"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.ID,
		arg.CategoryID,
		arg.StatusID,
		arg.Description,
		arg.ExternalDetails,
		arg.IdempotencyKey,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.CategoryID,
		&i.StatusID,
		&i.Description,
		&i.ExternalDetails,
		&i.IdempotencyKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAccountForWithdrawUpdate = `-- name: GetAccountForWithdrawUpdate :one
SELECT a.id, a.status_id, ab.balance::text, ab.credit_limit::text
FROM accounts a
         JOIN account_balances ab ON a.id = ab.account_id
WHERE a.public_id = $1
    FOR NO KEY UPDATE
`

type GetAccountForWithdrawUpdateRow struct {
	ID            int64       `json:"id"`
	StatusID      pgtype.Int4 `json:"status_id"`
	AbBalance     string      `json:"ab_balance"`
	AbCreditLimit string      `json:"ab_credit_limit"`
}

func (q *Queries) GetAccountForWithdrawUpdate(ctx context.Context, publicID pgtype.UUID) (GetAccountForWithdrawUpdateRow, error) {
	row := q.db.QueryRow(ctx, getAccountForWithdrawUpdate, publicID)
	var i GetAccountForWithdrawUpdateRow
	err := row.Scan(
		&i.ID,
		&i.StatusID,
		&i.AbBalance,
		&i.AbCreditLimit,
	)
	return i, err
}

const subtractAccountBalance = `-- name: SubtractAccountBalance :exec
UPDATE account_balances
SET balance = balance - $1
WHERE account_id = $2
`

type SubtractAccountBalanceParams struct {
	Balance   pgtype.Numeric `json:"balance"`
	AccountID int64          `json:"account_id"`
}

func (q *Queries) SubtractAccountBalance(ctx context.Context, arg SubtractAccountBalanceParams) error {
	_, err := q.db.Exec(ctx, subtractAccountBalance, arg.Balance, arg.AccountID)
	return err
}
