// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transaction_history.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAccountTransactions = `-- name: GetAccountTransactions :many
SELECT
    t.id AS transaction_id,
    t.category_id,
    t.status_id,
    t.description,
    t.created_at,
    p.amount::text AS amount_str,
    p.currency_code
FROM transactions t
JOIN postings p ON t.id = p.transaction_id
WHERE p.account_id = $1
ORDER BY t.created_at DESC
LIMIT $3 OFFSET $2
`

type GetAccountTransactionsParams struct {
	AccountID pgtype.Int8 `json:"account_id"`
	Offset    int32       `json:"offset"`
	Limit     int32       `json:"limit"`
}

type GetAccountTransactionsRow struct {
	TransactionID pgtype.UUID        `json:"transaction_id"`
	CategoryID    pgtype.Int4        `json:"category_id"`
	StatusID      pgtype.Int4        `json:"status_id"`
	Description   pgtype.Text        `json:"description"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	AmountStr     string             `json:"amount_str"`
	CurrencyCode  pgtype.Text        `json:"currency_code"`
}

func (q *Queries) GetAccountTransactions(ctx context.Context, arg GetAccountTransactionsParams) ([]GetAccountTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getAccountTransactions, arg.AccountID, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAccountTransactionsRow
	for rows.Next() {
		var i GetAccountTransactionsRow
		if err := rows.Scan(
			&i.TransactionID,
			&i.CategoryID,
			&i.StatusID,
			&i.Description,
			&i.CreatedAt,
			&i.AmountStr,
			&i.CurrencyCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
