version: '3.8'

services:
  # ==========================================
  # ИНФРАСТРУКТУРА
  # ==========================================
  postgres:
    image: postgres:17-alpine
    container_name: bank_postgres
    environment:
      POSTGRES_USER: bank_admin
      POSTGRES_PASSWORD: secretpassword
      POSTGRES_DB: accounts_db
    ports:
      - "5499:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./postgres-init/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U bank_admin -d accounts_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4
    container_name: bank_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@bank.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: bank_redis
    command: redis-server --appendonly yes
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: bank_rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: rmq_admin
      RABBITMQ_DEFAULT_PASS: secretpassword
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  db-migration:
    image: migrate/migrate
    container_name: bank_db_migration
    volumes:
      - ../src/service-account/migrations:/migrations
    command:
      - -path=/migrations
      - -database=postgresql://bank_admin:secretpassword@postgres:5432/accounts_db?sslmode=disable
      - up
    depends_on:
      postgres:
        condition: service_healthy

  vault-db-migration:
    image: migrate/migrate
    container_name: bank_vault_db_migration
    volumes:
      - ../src/service-card-secure/migrations:/migrations
    command:
      - -path=/migrations
      - -database=postgresql://bank_admin:secretpassword@postgres:5432/vault_db?sslmode=disable
      - up
    depends_on:
      postgres:
        condition: service_healthy

  # ==========================================
  # МИКРОСЕРВИСЫ
  # ==========================================

  service-card-secure:
    container_name: service_card_secure
    build:
      context: ../
      dockerfile: src/service-card-secure/Dockerfile
    environment:
      - APP_SECURITY__MASTER_KEY=supersecret32bytemasterkey123456
      - APP_DATABASE__URL=postgres://bank_admin:secretpassword@postgres:5432/vault_db?sslmode=disable
      - APP_SERVER__GRPC_PORT=50051
    ports:
      - "50051:50051"
    depends_on:
      postgres:
        condition: service_healthy
      vault-db-migration:
        condition: service_completed_successfully
    restart: unless-stopped

  service-exchanger:
    container_name: service_exchanger
    build:
      context: ../src/service-investment-and-exchange
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    restart: unless-stopped

  service-account:
    container_name: service_account
    build:
      context: ../src/service-account
      dockerfile: Dockerfile
    environment:
      - CONFIG_PATH=config/prod.yaml
      - REDIS_URL=redis:6379
      - EXCHANGER_URL=http://service-exchanger:8085/api/v1/rates
    ports:
      - "8081:8080"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      service-exchanger:
        condition: service_started
      db-migration:
        condition: service_completed_successfully
    restart: unless-stopped

  service-notification:
    container_name: service_notification
    build:
      context: ../src/service-notification
      dockerfile: Dockerfile
    environment:
      - CONFIG_PATH=config/local.yaml
      - RABBITMQ_URL=amqp://rmq_admin:secretpassword@rabbitmq:5672/
    depends_on:
      - rabbitmq
    restart: unless-stopped

  api-gateway:
    image: nginx:alpine
    container_name: api_gateway
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - service-account
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
  rabbitmq_data: