server:
  grpc_port: 50051

database:
  url: "postgres://bank_admin:secretpassword@postgres:5432/vault_db?sslmode=disable"
  max_connections: 5

security:
  master_key: "supersecret32bytemasterkey123456"