CREATE TABLE "currencies"
(
    "code"     varchar(10) PRIMARY KEY,
    "name"     varchar(50),
    "exponent" int DEFAULT 2
);

CREATE TABLE "transaction_categories"
(
    "id"       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name"     varchar(100),
    "mcc_code" int
);

CREATE TABLE "transaction_statuses"
(
    "id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(50)
);

CREATE TABLE "account_types"
(
    "id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(50)
);

CREATE TABLE "transaction_source_types"
(
    "id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(50) UNIQUE NOT NULL
);

CREATE TABLE "account_statuses"
(
    "id"   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" varchar(50)
);

CREATE TABLE "users"
(
    "id"         uuid PRIMARY KEY,
    "username"   varchar(50) UNIQUE,
    "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "accounts"
(
    "id"            bigserial PRIMARY KEY,
    "public_id"     uuid UNIQUE,
    "user_id"       uuid,
    "type_id"       int,
    "status_id"     int,
    "currency_code" varchar(10),
    "name"          varchar(100),
    "version"       int         DEFAULT 1,
    "created_at"    timestamptz DEFAULT (now()),
    "updated_at"    timestamptz DEFAULT (now())
);

CREATE TABLE "account_balances"
(
    "account_id"   bigint PRIMARY KEY,
    "balance"      numeric(78, 0) DEFAULT 0,
    "credit_limit" numeric(78, 0) DEFAULT 0,
    "updated_at"   timestamptz
);

CREATE TABLE "transactions"
(
    "id"                  uuid PRIMARY KEY,
    "source_type_id"      int,
    "source_id"           uuid,
    "destination_type_id" int,
    "destination_id"      uuid,
    "category_id"         int,
    "status_id"           int,
    "description"         text,
    "external_details"    jsonb,
    "idempotency_key"     varchar(255) UNIQUE,
    "created_at"          timestamptz DEFAULT (now()),
    "updated_at"          timestamptz DEFAULT (now())
);

CREATE TABLE "cards"
(
    "id"          uuid PRIMARY KEY,
    "account_id"  bigint,
    "pan_mask"    varchar(20),
    "expiry_date" date,
    "is_virtual"  boolean     DEFAULT false,
    "status"      varchar(20) DEFAULT 'active',
    "created_at"  timestamptz DEFAULT (now())
);

CREATE TABLE "postings"
(
    "id"             bigserial PRIMARY KEY,
    "transaction_id" uuid,
    "account_id"     bigint,
    "amount"         numeric(78, 0) NOT NULL,
    "currency_code"  varchar(10),
    "exchange_rate"  numeric(20, 10) DEFAULT 1
);

CREATE TABLE "recurring_payments"
(
    "id"                  uuid PRIMARY KEY,

    "source_type_id"      int NOT NULL,
    "source_id"           uuid NOT NULL,

    "destination_type_id" int,
    "destination_id"      uuid,

    "amount"              numeric(78, 0) NOT NULL,
    "currency_code"       varchar(10),
    "category_id"         int,
    "cron_expression"     varchar(50) NOT NULL,
    "next_execution_time" timestamptz NOT NULL,
    "is_active"           boolean DEFAULT true,
    "description"         text,
    "created_at"          timestamptz DEFAULT (now()),
    "updated_at"          timestamptz DEFAULT (now())
);

-- КОММЕНТАРИИ
COMMENT ON COLUMN "currencies"."code" IS 'ISO 4217: USD, RUB, JPY';
COMMENT ON COLUMN "currencies"."exponent" IS 'Количество копеек. 2 для USD/RUB, 0 для JPY';
COMMENT ON COLUMN "transaction_categories"."mcc_code" IS 'ISO 18245';
COMMENT ON COLUMN "transaction_statuses"."name" IS 'pending, posted, failed, rolled_back';
COMMENT ON COLUMN "account_types"."name" IS 'current, credit, savings';
COMMENT ON COLUMN "account_statuses"."name" IS 'active, frozen, blocked, closed';
COMMENT ON COLUMN "users"."id" IS 'ID from SSO';
COMMENT ON COLUMN "accounts"."public_id" IS 'Для API';
COMMENT ON COLUMN "accounts"."version" IS 'Optimistic Locking';
COMMENT ON COLUMN "account_balances"."balance" IS 'Сумма всех postings. Кэш.';
COMMENT ON COLUMN "cards"."pan_mask" IS '4276 **** **** 9999';
COMMENT ON COLUMN "cards"."status" IS 'active, blocked, expired';
COMMENT ON COLUMN "transactions"."external_details" IS 'Данные от провайдера, device_id и т.д.';
COMMENT ON COLUMN "postings"."amount" IS 'Отрицательное = списание, Положительное = зачисление';
COMMENT ON COLUMN "postings"."exchange_rate" IS 'Курс к базовой валюте системы или кросс-курс';
COMMENT ON COLUMN "recurring_payments"."destination_id" IS 'Null если это вывод во вне'; -- ИСПРАВЛЕНО

-- ВНЕШНИЕ КЛЮЧИ (FOREIGN KEYS)
ALTER TABLE "accounts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
ALTER TABLE "accounts" ADD FOREIGN KEY ("type_id") REFERENCES "account_types" ("id");
ALTER TABLE "accounts" ADD FOREIGN KEY ("status_id") REFERENCES "account_statuses" ("id");
ALTER TABLE "accounts" ADD FOREIGN KEY ("currency_code") REFERENCES "currencies" ("code");

ALTER TABLE "account_balances" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");
ALTER TABLE "cards" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");

ALTER TABLE "transactions" ADD FOREIGN KEY ("category_id") REFERENCES "transaction_categories" ("id");
ALTER TABLE "transactions" ADD FOREIGN KEY ("status_id") REFERENCES "transaction_statuses" ("id");
ALTER TABLE "transactions" ADD FOREIGN KEY ("source_type_id") REFERENCES "transaction_source_types" ("id");
ALTER TABLE "transactions" ADD FOREIGN KEY ("destination_type_id") REFERENCES "transaction_source_types" ("id");

ALTER TABLE "postings" ADD FOREIGN KEY ("transaction_id") REFERENCES "transactions" ("id");
ALTER TABLE "postings" ADD FOREIGN KEY ("account_id") REFERENCES "accounts" ("id");
ALTER TABLE "postings" ADD FOREIGN KEY ("currency_code") REFERENCES "currencies" ("code");

ALTER TABLE "recurring_payments" ADD FOREIGN KEY ("source_type_id") REFERENCES "transaction_source_types" ("id");
ALTER TABLE "recurring_payments" ADD FOREIGN KEY ("destination_type_id") REFERENCES "transaction_source_types" ("id");
ALTER TABLE "recurring_payments" ADD FOREIGN KEY ("currency_code") REFERENCES "currencies" ("code");
ALTER TABLE "recurring_payments" ADD FOREIGN KEY ("category_id") REFERENCES "transaction_categories" ("id");

INSERT INTO "transaction_source_types" ("name") VALUES ('account'), ('card');