DROP TABLE IF EXISTS "recurring_payments" CASCADE;
DROP TABLE IF EXISTS "postings" CASCADE;
DROP TABLE IF EXISTS "transactions" CASCADE;
DROP TABLE IF EXISTS "cards" CASCADE;

DROP TABLE IF EXISTS "account_balances" CASCADE;
DROP TABLE IF EXISTS "accounts" CASCADE;
DROP TABLE IF EXISTS "users" CASCADE;

DROP TABLE IF EXISTS "account_statuses" CASCADE;
DROP TABLE IF EXISTS "account_types" CASCADE;
DROP TABLE IF EXISTS "transaction_statuses" CASCADE;
DROP TABLE IF EXISTS "transaction_categories" CASCADE;
DROP TABLE IF EXISTS "transaction_source_types" CASCADE;
DROP TABLE IF EXISTS "currencies" CASCADE;